// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SistemaPagos.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250811155256_ModificacionLongitudClave")]
    partial class ModificacionLongitudClave
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DetallePlanillaModel", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Afp")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("IdPlanilla")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Isss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Renta")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SalarioBruto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdPlanilla");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("NotificacionModel", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdPlanilla")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Leida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdPlanilla");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("PlanillaModel", b =>
                {
                    b.Property<int>("IdPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCorte")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombrePlanilla")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPlanilla");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Planillas");
                });

            modelBuilder.Entity("SistemaPagos.Server.Models.UsuarioModel", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DetallePlanillaModel", b =>
                {
                    b.HasOne("PlanillaModel", "Planilla")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaPagos.Server.Models.UsuarioModel", "Usuario")
                        .WithMany("Detalles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Planilla");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NotificacionModel", b =>
                {
                    b.HasOne("PlanillaModel", "Planilla")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaPagos.Server.Models.UsuarioModel", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planilla");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlanillaModel", b =>
                {
                    b.HasOne("SistemaPagos.Server.Models.UsuarioModel", "Usuario")
                        .WithMany("Planillas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlanillaModel", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("SistemaPagos.Server.Models.UsuarioModel", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Notificaciones");

                    b.Navigation("Planillas");
                });
#pragma warning restore 612, 618
        }
    }
}
